import React from 'react';
import PageLayout from '../layouts/PageLayout';
import PageHeader from '../shared/PageHeader';
import SEO from '../shared/SEO';

// Importing the PDF links
import pdfLinks from '../../data/pdfLinks.json';

const ResearchScreen = (): React.ReactElement => {
  return (
    <PageLayout>
      <SEO title="Working Papers" description="List of my working papers" />
      <PageHeader>Working Papers</PageHeader>

      {/* Job Market Paper */}
      <div className="mt-6">
        <h2 className="text-xl font-bold">Talking to a Chatbot: AI Recommendations and Beliefs Updating</h2>
        <em><p className="font-italic">Job Market Paper</p></em>
        <p className="mt-2">
          <strong>Abstract:</strong> This study investigates whether AI-powered chatbots are more persuasive than static
          sources of information. In a lab experiment, participants reported their beliefs about the correct answer to a
          series of logical reasoning questions both before and after receiving recommendations generated by GPT-3.5
          Turbo.
          In one treatment, participants received real-time recommendations from a chatbot, while in the other, they
          received
          static, pre-generated recommendations. The informational content of the recommendations, including both the
          recommended answers and the reasoning behind them, was distributionally matched across treatments.
          Participants who
          interacted with the chatbot were slightly more likely to update their beliefs following the AI
          recommendations,
          with a 31.46 percentage point change compared to 26.31 in the static treatment (p &lt; 0.084). Further
          analyses reveal
          that the chatbot was especially persuasive among participants whose initial beliefs clashed with the
          recommendations.
        </p>
        <p className="mt-4">
          <em><a href={pdfLinks.jobMarketPaper.url} target="_blank" rel="noopener noreferrer">[Link to download
            paper]</a></em>
        </p>
        <p className="mt-4">
          <em><a href={pdfLinks.JMP_deepdive.url} target="_blank" rel="noopener noreferrer">[DeepDive podcast]</a></em>
        </p>
      </div>

      {/* Monitoring as a Service */}
      <div className="mt-8">
        <h2 className="text-xl font-bold">Monitoring as a Service</h2>
        <p className="mt-2">
          <strong>Abstract:</strong> Can a monitoring service help people mitigate procrastination and commit to their plans?
          I conducted a longitudinal real-effort experiment in which subjects were required to complete 80 tasks over three
          sessions in three weeks and make non-binding plans of how many tasks they want to complete in the subsequent two
          weeks. Subjects were randomly assigned to either a <em>Control</em> group or a <em>Monitored</em> group. In the
          Monitored group, after making their plans, subjects connected with a monitor via WhatsApp and were informed that
          their progress would be observed and that they would receive reminders to meet deadlines if they delayed their work.
          I found that the monitoring service improved the rate at which subjects met their plans by 12.75 percentage points
          (p &lt; 0.05) and improved the completion rate of the experiment by 19.47 percentage points (p &lt; 0.001). These effects
          were primarily driven by a reduction in dropout rates. Additionally, subjects who received the monitoring service
          delayed their starting time by more than an hour. Further research is needed to disentangle the specific role of
          reminders in this commitment device. Overall, the findings suggest that monitoring services can be an effective tool
          to mitigate procrastination and improve commitment.
        </p>
        <p className="mt-4">
          <em><a href="#" target="_blank" rel="noopener noreferrer">[Manuscript available soon]</a></em>
        </p>
      </div>

      {/* Emotional Discrimination */}
      <div className="mt-8">
        <h2 className="text-xl font-bold">Emotional Discrimination</h2>
        <em><p className="font-italic">(with Sigrid Suetens and Boris van Leeuwen)</p></em>
        <p className="mt-2">
          <strong>Abstract:</strong> While ethnic discrimination is still a major concern, not much is known about the role of
          emotions on discrimination itself. We conducted an online experiment where native Dutch participants, playing the
          responder role, received a low offer from a proposer with either a native Dutch name or an ethnic minority name, and
          had to decide whether to accept or reject this low offer. Their emotions could be triggered in some treatments where
          they actually <em>experienced</em> the low offer before making a choice. We found that the responders did not
          discriminate nor react emotionally, as we did not find significant treatment effects on the rejection rate to the
          low offer.
        </p>
        <p className="mt-4">
          <em><a href="#" target="_blank" rel="noopener noreferrer">[Manuscript available soon]</a></em>
        </p>
      </div>
    </PageLayout>
  );
};

export default ResearchScreen;
